# Print Two number

In [2]:
a=5
b=7
print (a)
print (b)

5
7


# swap two number without using thrid variable

In [5]:
a,b = b, a
print(a)
print(b)

7
5


# Condition in python


In [14]:
a=3
b=9
if b%a==0:
    print("b is divisible by a")
elif b+1==10:
    print("Increment in b produce 10")
else:
    print("you r in else statement")

b is divisible by a


In [17]:
def checkDivisibility(a, b):
    if a%b ==0:
        print("a  is divisible by b")
    else:   
        print("a is not divisible by b")
        
checkDivisibility(4,2)

a  is divisible by b


In [18]:
a = "This is a String"
print (a)

This is a String


# List in Python

In [23]:
L = [1, "a", "string", 1+2]
print(L)
L.append(6)
print (L)
L.pop()
print(L)
print (L[1])

[1, 'a', 'string', 3]
[1, 'a', 'string', 3, 6]
[1, 'a', 'string', 3]
a


Tuples:
    A tuples is a sequence of immutable python object. Tuples are just like lists with the exception that tuples
    cannot be changed once decalred. Tuples are faster than lists

In [24]:
tup = (1, "a", "string", 1+2)
print (tup)
print (tup[1])


(1, 'a', 'string', 3)
a


In [30]:
i = 1
while(i<10):
    i +=1
    print (i),

2
3
4
5
6
7
8
9
10


# Take a string and split them

In [31]:
s = "Hello World"
for i in s:
    print(i)

H
e
l
l
o
 
W
o
r
l
d


# What is the msximum possible value of sn integer in python.?


In [33]:
x =  1000000000000000000000000000
x =x +1
print(x)

1000000000000000000000000001


In [34]:
x = 10
print(type(x))

<class 'int'>


# Transpose a matrix in single line in python

In [40]:
m = [[1,2],[3,4],[5,6]]
for row in m:
    print(row)

print("\n")
rez = [[m[j][i] for j in range(len(m))] for i in range(len(m[0]))]
for row in rez:
    print(row)

[1, 2]
[3, 4]
[5, 6]


[1, 3, 5]
[2, 4, 6]


# Create a matrix and transform the matrix

In [44]:
matrix = [(1,2,3), (4,5,6),(7,8,9),(10,11,12)]
for row in matrix:
    print(row)
    
print("\n")
t_matrix = zip(*matrix)
for row in t_matrix:
    print(row)

(1, 2, 3)
(4, 5, 6)
(7, 8, 9)
(10, 11, 12)


(1, 4, 7, 10)
(2, 5, 8, 11)
(3, 6, 9, 12)


# Create a matrix and transpose it using numpy

In [47]:
import numpy
matrix = [[1,2,3],[4,5,6], [7,8,9]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Global and Local variables in python

In [48]:

# this function uses global variable s.

def f():
    print (s)
    

# global scope.
s = "I luv u python"
f()

I luv u python


In [52]:

def f():
    #s = "Me too"
    print(s)
    
# global Scope.
s = "I luv python"
f()
print(s)

I luv python
I luv python


In [51]:
def f():
    s = "Me too"
    print(s)
    
# global Scope.
s = "I luv python"
f()
print(s)

Me too
I luv python


In [53]:

# This is function modifies  global variable 's'.

def f():
    global s
    print(s)
    s = "Look for GeeksforGeeks python Section"
    print(s)
    
#Global Scope.
s = "Python is great"
f()
print(s)

Python is great
Look for GeeksforGeeks python Section
Look for GeeksforGeeks python Section


In [54]:
a = 1

# Uses global because there is no local 'a'

def f():
    print ("Inside f():", a)
    
# Variable 'a' is redefine as a local.

def g():
    a = 2
    print("Inside g():", a)
    
# Use global keyword to modify global 'a'.

def h():
    global a
    a =3
    print("Inside h():", a)
    
# Global scope
print ("global:",a)
f()
print("Global:", a)
g()
print("global:", a)
h()
print("global:", a)

global: 1
Inside f(): 1
Global: 1
Inside g(): 2
global: 1
Inside h(): 3
global: 3


# Create  a function where we can print Employee name, age, sex and salary.

In [4]:
def printinfo(name, age,sex, salary):
    print("Name: ", name)
    print("Age: ", age)
    print("Sex: ", sex)
    print("Salary: ", salary)
    

printinfo(name="Somnath", age=24, sex="Male", salary=40000)

Name:  Somnath
Age:  24
Sex:  Male
Salary:  40000
